### ISSUE TITLE
Issue with visuals.

### ISSUE THREAD

**Issue by starsmoke** [AliTe/vjlxnr#1]
No matter what image I select, all I see are black spaces, in the 2 image slots and in the vjlxnr window.

**Comment by alite** [comment]
Did you drop a folder with PNG files onto the drop file zone of the device (the grey, framed area, right hand side, labeled with (German) "Bilderordner hierher ziehen")?

**Comment by starsmoke** [comment]
I did. I even tried your sample images in the "media" folder. I am running Live on XP, but I hardly ever run into problems.

**Comment by starsmoke** [comment]
I can select "img x" in the dropdown menus, but the squares remain black.

**Comment by alite** [comment]
Which Version of Live and Max/Max4Live are you running?
I built it with live 9.5 and Max 7.1 (on a Mac) …

**Comment by starsmoke** [comment]
Live 9.1 and Max 6.1. I will try to update some stuff and see if anything changes. I hope I get it to work, it looks badass.

**Comment by alite** [comment]
OK - this could be a problem, if you're on max 6.1 - I don't know if the max project is backwards-combatible - hm …

**Comment by alite** [comment]
One more question:
Do you see the filename of the choosen image below the preview area, or do you just see a '-'?
And does it change after selecting other menu entries?

**Comment by starsmoke** [comment]
Yes i see the filename and it does change with other selections. Unfortunately Max 7.1 isn't supported on Windows XP so I wont know if this is just a backwards compatibility problem.

**Comment by starsmoke** [comment]
I think I'm just going to have to accept that Im using some obsolete technology here. It's the computer I use for recording my music, so I was hoping I could slap this on to the master channel and see what happens. Guess Im gonna have to try to update my OS if I want to do it on that one.

**Comment by alite** [comment]
I'm sorry this is not working for you - I'm discussing this issue on several places at the moment. If we find a solution, I will post it here …

**Comment by alite** [comment]
… just tested with Max 6.1 - it is definitively not working …

**Comment by PsynapsDiskord** [comment]
I'm having the same problem listed by starsmoke - Im running live 9.5 and max7 on and win 7 pro pc...

**Comment by alite** [comment]
Meanwhile we figured out that:
- Possibly Versions below Live 9.5 / Max 7.1 will not work
- Should be running on 64 bit
- At least 8 GB of RAM are recommended

To find out the minmal system requirements, please include your hardware (and software) specs in your posts (Live/Max versions; OS; RAM; 32/64 bit; etc).

Succes seems to strongly depend on your media data and your choosen (image) resolution as all media data has to be kept in RAM!

**Comment by starsmoke** [comment]
PsynapsDiskord - Oh no... try to update to Max7.1 and try it (assuming you mean you have 7.0)... That will tell me if changing from XP to Win7 will help at all.

**Comment by PsynapsDiskord** [comment]
Success! Updated from Max 7.0.6 to 7.1 and it works!

**Comment by alite** [comment]
Great, I'm glad it works for you!
@PsynapsDiskord , @starsmoke thanks a lot for your support by reporting …

**Comment by alite** [comment]
OK, I updated 'system requirements' in README.
